/**
 * What a retention run could touch, and what it must never touch.
 *
 * There is no retention policy in this repository and this file does not invent
 * one. It has no default window: a caller states a cutoff or gets an error. The
 * period is the owner's decision and a number chosen here would end up in a
 * published notice as though somebody had decided it.
 *
 * Nothing here deletes. It counts, so a policy can be chosen against real
 * figures instead of guesses, and so the shape of the eventual job is reviewable
 * before it is written. Every statement below is a `SELECT count(*)`, and
 * `countRetentionCandidates` refuses to run one that is not.
 *
 * Two different things are needed, and calling both "deletion" is how
 * accounting gets destroyed by a privacy job:
 *
 *   PRUNE       the row exists only to enforce a limit, and once it is past the
 *               window it enforces nothing. Deleting it loses nothing else.
 *   ANONYMISE   the row is financial and has to survive, but its link to a
 *               session does not. The money stays; the identifier goes.
 *
 * And some rows are neither, at any age, because an operator still has work to
 * do on them. Those are named explicitly rather than left to a date predicate.
 */

// The hourly bucket key, as the meter writes it. Imported rather than rewritten
// because a bucket comparison built from a second copy of the format would read
// the wrong rows the moment either copy changed.
import { hourKey } from "@/providers/usage/UsageMeter";

export type RetentionAction = "prune" | "anonymise" | "protected";

/**
 * Outcomes this application writes. Anything else in the column was written by
 * something else, and is counted separately rather than assumed finished.
 */
export const KNOWN_OUTCOMES = ["open", "billed", "not_billed", "uncertain", "legacy"] as const;

/**
 * Outcomes that mean the accounting on a row is finished. Deliberately an
 * allowlist: a row carrying an outcome nobody here recognises is left alone and
 * reported, rather than swept in by a "not open, not uncertain" predicate.
 * `uncertain` is finished only once `reconciled_at` is set, so it is handled in
 * the predicate rather than listed here.
 */
const SETTLED_OUTCOMES = ["billed", "not_billed", "legacy"] as const;

export type RetentionCategory = {
  id: string;
  table: string;
  action: RetentionAction;
  /** What the row is, in one line. */
  what: string;
  /** Why this action is the right one for it. */
  why: string;
  /**
   * A read-only count. `prune` and `anonymise` counts answer "how many rows
   * would this cutoff reach"; `protected` counts answer "how many rows are held
   * back whatever the cutoff", and ignore it.
   */
  count: { sql: string; params: (cutoff: Date) => unknown[] };
};

export const RETENTION_CATEGORIES: RetentionCategory[] = [
  {
    id: "client_buckets",
    table: "assistant_client",
    action: "prune",
    what: "One row per salted IP hash per hour, with a request count.",
    why:
      "It exists to enforce an hourly request limit and nothing else. An hour that has passed cannot be exceeded, so a bucket older than the cutoff enforces nothing and is the clearest thing on this list to delete. It is also the only table holding anything derived from an IP address.",
    // hour_bucket is TEXT in the fixed-width form YYYY-MM-DDTHH, so a string
    // comparison orders it correctly. That is only true because the width is
    // fixed; see hourKey.
    count: {
      sql: "SELECT count(*)::int AS n FROM assistant_client WHERE hour_bucket < $1",
      params: (cutoff) => [hourKey(cutoff)],
    },
  },
  {
    id: "sessions",
    table: "assistant_session",
    action: "prune",
    what: "One row per browser-generated session id, with a turn count and a first-seen time.",
    why:
      "It exists to enforce a per-session turn limit. The id is generated by the browser and tied to no account. A session past the cutoff is not going to take another turn under that limit.",
    count: {
      sql: "SELECT count(*)::int AS n FROM assistant_session WHERE first_seen < $1",
      params: (cutoff) => [cutoff.toISOString()],
    },
  },
  {
    id: "usage_session_link",
    table: "assistant_usage",
    action: "anonymise",
    what: "The session_id column on a settled, reconciled accounting row.",
    why:
      "The row is the ledger and has to survive: it carries the model, the tokens, the cost and the outcome, and deleting it would silently change what the site has spent. The session id is the only part that points at a visitor, and cost accounting does not need it once the charge is settled and reconciled. This is the one place where deleting the row would be the wrong answer and dropping a column is the right one.",
    count: {
      sql: `SELECT count(*)::int AS n FROM assistant_usage
             WHERE settled_at < $1
               AND session_id <> ''
               AND (outcome = ANY($2::text[]) OR (outcome = 'uncertain' AND reconciled_at IS NOT NULL))`,
      params: (cutoff) => [cutoff.toISOString(), [...SETTLED_OUTCOMES]],
    },
  },
  {
    id: "open_reservations",
    table: "assistant_usage",
    action: "protected",
    what: "Reservations taken and never settled (outcome 'open').",
    why:
      "Budget is held against them and no outcome was ever recorded. An operator has to close each one against the provider's record, and the session id is part of what identifies it. Age is not a reason to touch one: an old open reservation is more in need of attention, not less.",
    count: {
      sql: "SELECT count(*)::int AS n FROM assistant_usage WHERE outcome = 'open'",
      params: () => [],
    },
  },
  {
    id: "uncertain_charges",
    table: "assistant_usage",
    action: "protected",
    what: "Charges held as uncertain and not yet reconciled (outcome 'uncertain', reconciled_at IS NULL).",
    why:
      "The provider may have billed for these and nobody has checked. They count against the cap until somebody does. Anonymising or pruning one would remove the trail an operator needs to reconcile it.",
    count: {
      sql: "SELECT count(*)::int AS n FROM assistant_usage WHERE outcome = 'uncertain' AND reconciled_at IS NULL",
      params: () => [],
    },
  },
  {
    id: "unrecognised_outcomes",
    table: "assistant_usage",
    action: "protected",
    what: "Accounting rows carrying an outcome this code does not know.",
    why:
      "Nothing here can say whether such a row is finished, so it is left alone and shown as its own figure. A count above zero means the classification is out of date and the categories should be reviewed before any job is written, not that these rows are safe to sweep up.",
    count: {
      sql: "SELECT count(*)::int AS n FROM assistant_usage WHERE NOT (outcome = ANY($1::text[]))",
      params: () => [[...KNOWN_OUTCOMES]],
    },
  },
  {
    id: "budget_totals",
    table: "assistant_budget",
    action: "protected",
    what: "Monthly reserved, spent and uncertain totals.",
    why:
      "Aggregates only, with no personal data in them at all, and they are the financial history. Nothing in a retention job has any reason to touch this table.",
    count: {
      sql: "SELECT count(*)::int AS n FROM assistant_budget",
      params: () => [],
    },
  },
];

export type RetentionCounts = Record<string, number>;

export type RetentionReport = {
  cutoff: string;
  generatedAt: string;
  store: string;
  counts: RetentionCounts;
};

/**
 * The cutoff, stated explicitly or not at all.
 *
 * Accepts a date, `2026-06-30`, or a number of days to keep, `--retain-days=90`.
 * Rejects everything else, including an absent value, because a retention job
 * that runs with a default is a policy nobody chose.
 */
export function resolveCutoff(input: { before?: string; retainDays?: string }, now: Date): { ok: true; cutoff: Date; stated: string } | { ok: false; reason: string } {
  const both = input.before !== undefined && input.retainDays !== undefined;
  if (both) return { ok: false, reason: "Give --before or --retain-days, not both. They are two ways to say one thing and disagreeing about it is not something this should guess at." };

  if (input.before !== undefined) {
    if (!/^\d{4}-\d{2}-\d{2}$/.test(input.before)) return { ok: false, reason: `--before must be a date like 2026-06-30, not "${input.before}".` };
    const cutoff = new Date(`${input.before}T00:00:00.000Z`);
    if (Number.isNaN(cutoff.getTime())) return { ok: false, reason: `"${input.before}" is not a real date.` };
    if (cutoff.getTime() > now.getTime()) return { ok: false, reason: "That cutoff is in the future, which would count every row as eligible. Refusing rather than reporting that." };
    return { ok: true, cutoff, stated: `before ${input.before}` };
  }

  if (input.retainDays !== undefined) {
    if (!/^\d+$/.test(input.retainDays)) return { ok: false, reason: `--retain-days must be a whole number of days, not "${input.retainDays}".` };
    const days = Number(input.retainDays);
    if (days < 1) return { ok: false, reason: "--retain-days must be at least 1. Zero would make everything eligible the moment it was written." };
    return { ok: true, cutoff: new Date(now.getTime() - days * 86_400_000), stated: `keeping ${days} ${days === 1 ? "day" : "days"}` };
  }

  return {
    ok: false,
    reason:
      "No cutoff given. This has no default on purpose: the retention period is the site owner's decision, and a number invented here would end up in a published notice as though somebody had chosen it. Pass --before=YYYY-MM-DD or --retain-days=N.",
  };
}

/** The narrowest thing this needs from a database client. */
export type RetentionQuery = (sql: string, params: unknown[]) => Promise<{ rows: Record<string, unknown>[] }>;

// Anything that changes a row. Checked before each statement is sent, so this
// command cannot start writing through a later edit without the check being
// deleted first, which is a visible thing to do in a diff.
const FORBIDDEN = /\b(delete|update|insert|truncate|drop|alter|create|merge|grant)\b/i;

export function assertReadOnly(sql: string): void {
  const normalised = sql.trim().replace(/\s+/g, " ");
  if (!/^select count\(\*\)/i.test(normalised)) {
    throw new Error(`Retention statements may only count rows. Refusing: ${normalised.slice(0, 80)}`);
  }
  if (FORBIDDEN.test(normalised)) {
    throw new Error(`Retention statements may not modify anything. Refusing: ${normalised.slice(0, 80)}`);
  }
}

/**
 * Count what each category holds. Reads only, and reads only counts: no
 * statement here selects a session id, a client key, an amount or a row.
 */
export async function countRetentionCandidates(query: RetentionQuery, cutoff: Date): Promise<RetentionCounts> {
  const counts: RetentionCounts = {};
  for (const category of RETENTION_CATEGORIES) {
    assertReadOnly(category.count.sql);
    const result = await query(category.count.sql, category.count.params(cutoff));
    const n = Number(result.rows[0]?.n ?? 0);
    counts[category.id] = Number.isFinite(n) ? n : 0;
  }
  return counts;
}

/** The report, as text. Counts only: no identifier, no amount, no row. */
export function formatRetentionReport(report: RetentionReport): string {
  const lines: string[] = [];
  const at = (id: string) => report.counts[id] ?? 0;

  lines.push("Retention dry run. Nothing was deleted, changed or anonymised.");
  lines.push("");
  lines.push(`Store      ${report.store}`);
  lines.push(`Cutoff     ${report.cutoff}`);
  lines.push(`Run at     ${report.generatedAt}`);
  lines.push("");

  for (const action of ["prune", "anonymise", "protected"] as const) {
    const group = RETENTION_CATEGORIES.filter((c) => c.action === action);
    if (group.length === 0) continue;
    lines.push(
      action === "prune"
        ? "Older than the cutoff. A retention job, if one existed, would delete these"
        : action === "anonymise"
          ? "Older than the cutoff. A job would keep the row and drop the session link"
          : "Held whatever the cutoff. Counted here in full, not filtered by date",
    );
    for (const c of group) {
      lines.push(`  ${String(at(c.id)).padStart(8)}  ${c.table}.${c.id}`);
      lines.push(`            ${c.what}`);
    }
    lines.push("");
  }

  if (at("unrecognised_outcomes") > 0) {
    lines.push("One or more accounting rows carry an outcome this code does not recognise.");
    lines.push("They are counted above and classified as nothing. Review them before any");
    lines.push("job is written against these categories.");
    lines.push("");
  }

  lines.push("No retention job exists. This command reports and does nothing else.");
  lines.push("The period is not set here: it is the site owner's to choose, and this");
  lines.push("run used only the cutoff given on the command line.");
  return lines.join("\n");
}
