import { z } from "zod";
import { INTENT_LIMITS, ModelIntent } from "@/domain/assistant";
import { CONDITION_OPS } from "@/domain/category";
import { DEFAULT_BASE_URL, OPENAI_HOST } from "@/domain/credential";
import { MONEY_CURRENCY } from "@/domain/money-contract";
import { SOFT_DIRECTIONS, SOFT_WEIGHT_RANGE } from "@/domain/personalization";
import { buildRejection, captureRejectedIntent } from "@/providers/ai/diagnostics";
import { estimateTokens } from "@/providers/usage/UsageMeter";

// Called over plain fetch. No SDK dependency to pin, patch or audit.
// The key is read from the environment on the server only and never reaches a
// response body, a log line or the browser bundle.

// Three tiers, not two. A value whose provenance is recorded as unknown is not
// a manufacturer's claim, and presenting it as one invents an attribution the
// catalogue never made. Placeholder values are still withheld entirely.
export const EVIDENCE_TIERS = ["sourced", "manufacturer_claim", "unattributed"] as const;
export type Evidence = (typeof EVIDENCE_TIERS)[number];
export type GroundedFact = { label: string; value: string; evidence: Evidence };
export type GroundedProduct = {
  id: string;
  name: string;
  brand: string;
  // Null when the catalogue's price is a placeholder: it is withheld, not
  // labelled, so it cannot be quoted.
  price: string | null;
  priceIsPlaceholder: boolean;
  facts: GroundedFact[];
  notStated: string[];
};

export type ConverseInput = {
  categoryName: string;
  filterVocabulary: string;
  // Generated by moneyContractText from the same code that converts the
  // amounts, so the model cannot be told one unit and validated against
  // another.
  moneyContract: string;
  // A shortlist, never the whole catalogue. `catalogueSize` is how many
  // published products the category actually holds, so the model can be told
  // plainly that what it sees is partial and must not be treated as the set.
  products: GroundedProduct[];
  catalogueSize: number;
  messages: { role: "user" | "assistant"; text: string }[];
  activeConstraints: string[];
};

export type TokenUsage = { inputTokens: number; outputTokens: number };

export type ConverseResult = {
  intent: ModelIntent;
  model: string;
  // Null when the provider answered but did not report usable token counts.
  // The caller must then treat the cost as unknown rather than as zero.
  usage: TokenUsage | null;
  // "unreadable" means the provider answered and nothing usable came back. The
  // intent is a placeholder, NOT an answer: its empty `hard` and `soft` say
  // that nothing was understood, not that the shopper asked for nothing. A
  // caller that treats them as an answer proposes clearing the shopper's
  // filters on the strength of a reply it could not read.
  status: "ok" | "unreadable";
};

// Carries whether the provider could have charged for the attempt. Anything
// the provider rejected before inference is free; anything that was sent and
// then went dark is not known to be free and must not be treated as such.
export class ProviderCallError extends Error {
  constructor(
    message: string,
    readonly billable: "not_billed" | "uncertain",
  ) {
    super(message);
    this.name = "ProviderCallError";
  }
}

export interface ConversationProvider {
  readonly name: string;
  readonly isLive: boolean;
  // Estimated prompt size in tokens, so the caller can refuse to send a
  // request larger than it reserved budget for.
  estimatePromptTokens(input: ConverseInput): number;
  converse(input: ConverseInput): Promise<ConverseResult>;
}

// The instructions the model gets are generated from the same constants that
// validate its answer, so the contract cannot drift away from the validator.
// It drifted once: the schema enforced two closed enums that the prompt never
// named, and every reply carrying a constraint was discarded whole.
const OPS = CONDITION_OPS.join(" | ");
const DIRECTIONS = SOFT_DIRECTIONS.join(" | ");

const SYSTEM = `You help someone choose between products on a comparison site.

Your job is to understand what they need and turn it into structured filters. You do NOT decide which product is best: the site's own ranking engine does that and its result is shown alongside your reply. Never claim a product is best, top-rated or recommended by you.

Rules you must follow:
1. Only ever refer to products and figures given to you in the CATALOGUE block. Never introduce a product, brand, price or specification that is not there. If asked something the catalogue does not answer, say the information is not stated.
2. Distinguish evidence, every time you use a figure.
   - "sourced" was independently verified. State it plainly.
   - "manufacturer_claim" is what the maker says, not a measurement. Say whose claim it is when you rely on it, for example "the maker reports 189 mW/cm2".
   - "unattributed" means the value is recorded but its source is not. Say that its source is not recorded, or do not use it.
   - a field under "not stated" is unknown. Never estimate it.
3. The CATALOGUE block is a SHORTLIST, not the catalogue. It holds at most the products listed, out of a larger category, and it was chosen before you replied. So you cannot see what is missing from it. Never say that no product exists, that nothing meets a constraint, that something is unavailable, or that a count is complete. If nothing in the shortlist fits, say that about the shortlist only, and still put the constraint in "hard": the site's engine searches every product and reports the real count beside your reply.
4. Ask about budget, intended use, space and preferences when they are still unknown, one question at a time, and offer a few concrete options.
5. If a constraint the shopper gave cannot be met, do NOT silently drop it. Say what does not fit and ask whether they want to relax it.
6. These are wellness products. Help with the shopping decision only. Never say or imply a product treats, cures, prevents, diagnoses or relieves any medical condition, and never give personalized medical advice. If asked, set medicalIntent true, say plainly that you cannot answer that, and offer to compare on specifications instead.
7. Be brief. Two or three sentences.

OUTPUT CONTRACT. Reply with a single JSON object and nothing else. Every field below is validated exactly as written. A reply that breaks any one of these rules is discarded whole and the shopper sees an error instead of your answer, so follow them literally.

{"reply": string, "hard": [{"key","op","value"}], "soft": [{"key","direction","value","weight"}], "unmapped": [string], "question": {"text","options":[string]} | null, "medicalIntent": boolean, "suggestCompare": [productId]}

- reply: required string, at most ${INTENT_LIMITS.replyChars} characters.
- hard: array of at most ${INTENT_LIMITS.hard} entries.
  - key: one of the keys listed in FILTERS. No other key.
  - op: EXACTLY one of these words: ${OPS}. Not a symbol, not a synonym, not "less_than", not "<", not "under".
  - value: a number, string, boolean, array of strings, or array of numbers. Omit it only with op ${CONDITION_OPS[CONDITION_OPS.length - 2]} or ${CONDITION_OPS[CONDITION_OPS.length - 1]}. For the money keys named in the MONEY block, the value is an object, not a number.
- soft: array of at most ${INTENT_LIMITS.soft} entries.
  - key: one of the keys listed in FILTERS.
  - direction: EXACTLY one of these words: ${DIRECTIONS}. Not "low", not "lower", not "minimize", not "cheap".
  - weight: a number from ${SOFT_WEIGHT_RANGE.min} to ${SOFT_WEIGHT_RANGE.max} inclusive. Use ${SOFT_WEIGHT_RANGE.default} if you have no reason to prefer another.
  - value: optional, same types as above.
- unmapped: at most ${INTENT_LIMITS.unmapped} strings.
- question: null, or {"text": at most ${INTENT_LIMITS.questionChars} characters, "options": at most ${INTENT_LIMITS.questionOptions} strings of at most ${INTENT_LIMITS.questionOptionChars} characters each}.
- medicalIntent: boolean.
- suggestCompare: at most ${INTENT_LIMITS.suggestCompare} product ids taken from the CATALOGUE.

Repeat every constraint that still applies, not just new ones. Use "unmapped" for anything the shopper cares about that the filters cannot express.`;

export class OpenAIConversationProvider implements ConversationProvider {
  readonly name = "openai";
  readonly isLive = true;

  // `apiKey` is null in proxy-credential mode: the agent proxy attaches the
  // credential outside this process, so no authorization header is sent.
  constructor(
    private readonly apiKey: string | null,
    private readonly model = process.env.OPENAI_MODEL ?? "gpt-4o-mini",
    private readonly baseUrl = process.env.OPENAI_BASE_URL ?? DEFAULT_BASE_URL,
    private readonly maxOutputTokens = Number(process.env.ASSISTANT_MAX_OUTPUT_TOKENS ?? 500),
    private readonly timeoutMs = Number(process.env.ASSISTANT_TIMEOUT_MS ?? 20000),
  ) {}

  private buildMessages(input: ConverseInput) {
    const catalogue = input.products
      .map((p) => {
        const facts = p.facts.map((f) => `    ${f.label}: ${f.value} [${f.evidence}]`).join("\n");
        const missing = p.notStated.length > 0 ? `\n    not stated: ${p.notStated.join(", ")}` : "";
        const price = p.price === null ? "not stated" : `${p.price} [sourced]`;
        return `  ${p.id} | ${p.brand} ${p.name} | price ${price}\n${facts}${missing}`;
      })
      .join("\n");

    const context = [
      `CATEGORY: ${input.categoryName}`,
      `FILTERS: ${input.filterVocabulary}`,
      input.moneyContract,
      input.activeConstraints.length > 0 ? `ALREADY AGREED: ${input.activeConstraints.join("; ")}` : "ALREADY AGREED: nothing yet",
      // Stated as a count, in the block itself, because a model that is not
      // told the list is partial will answer as though it is complete. It did:
      // it reported that nothing under $500 existed while the engine matched a
      // product that was ranked just outside this shortlist.
      `CATALOGUE: a shortlist of ${input.products.length} of the ${input.catalogueSize} products in this category, chosen before your reply. You cannot see the other ${Math.max(0, input.catalogueSize - input.products.length)}. Do not describe this list as the catalogue and do not claim anything about products missing from it.\n${catalogue}`,
    ].join("\n\n");

    return [
      { role: "system" as const, content: SYSTEM },
      { role: "system" as const, content: context },
      ...input.messages.map((m) => ({ role: m.role, content: m.text })),
    ];
  }

  estimatePromptTokens(input: ConverseInput): number {
    return estimateTokens(this.buildMessages(input).map((m) => m.content).join("\n"));
  }

  async converse(input: ConverseInput): Promise<ConverseResult> {
    // One deadline for the whole exchange. Clearing it once headers arrive
    // would leave a stalled body to hang until the platform killed the
    // function, with the reservation still open and no outcome recorded.
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeoutMs);
    try {
      return await this.exchange(input, controller.signal);
    } finally {
      clearTimeout(timer);
    }
  }

  private async exchange(input: ConverseInput, signal: AbortSignal): Promise<ConverseResult> {
    // Second guard behind the credential resolver. An unauthenticated request
    // must only ever leave for the one host whose credential the proxy holds.
    if (this.apiKey === null && !isOpenAiHost(this.baseUrl)) {
      throw new ProviderCallError("The assistant is misconfigured and no request was made.", "not_billed");
    }

    const headers: Record<string, string> = { "content-type": "application/json" };
    if (this.apiKey !== null) headers.authorization = `Bearer ${this.apiKey}`;

    let res: Response;
    try {
      res = await fetch(`${this.baseUrl}/chat/completions`, {
        method: "POST",
        headers,
        signal,
        body: JSON.stringify({
          model: this.model,
          temperature: 0.2,
          // Bounds the output side of the reservation. Without it the provider
          // would be free to generate far more than the budget assumed.
          max_tokens: this.maxOutputTokens,
          // Schema-constrained output would let the provider reject a bad shape
          // before it is billed for, instead of this application discarding it
          // after. It is NOT on by default: whether this model and this account
          // support `json_schema` with `strict` has not been verified against
          // the API, and changing the request on an assumption is how a working
          // integration breaks. Set ASSISTANT_RESPONSE_FORMAT=json_schema to try
          // it, verify one call, then decide. Application validation runs either
          // way and is not relaxed by this.
          response_format: responseFormat(),
          messages: this.buildMessages(input),
        }),
      });
    } catch (e) {
      throw connectionError(e, "before");
    }

    if (!res.ok) {
      // Never surface the provider's body to the client: it can echo headers.
      throw await statusError(res);
    }

    let json: {
      choices?: { message?: { content?: string }; finish_reason?: string }[];
      usage?: { prompt_tokens?: number; completion_tokens?: number };
    };
    try {
      json = await res.json();
    } catch (e) {
      // The provider answered 200, so inference ran and was charged. Whether
      // the body stalled, was truncated or was not JSON, we cannot read the
      // cost, and the timeout above still applies to this read.
      throw connectionError(e, "after");
    }

    const raw = json.choices?.[0]?.message?.content ?? "";
    const finishReason = json.choices?.[0]?.finish_reason ?? null;

    // Unparseable output is a rejection, not an empty answer. It used to become
    // `{}`, which normalize filled with empty arrays and an empty reply, and
    // which the schema's defaults then accepted: a truncated reply became a
    // successful blank one, invisible to diagnostics. A reply the shopper can
    // read is required, so an empty one fails here too.
    let parsedJson: unknown;
    try {
      parsedJson = JSON.parse(raw);
    } catch {
      const failure = new z.ZodError([
        { code: "custom", path: ["(body)"], message: `The reply was not JSON. finish_reason=${finishReason ?? "unknown"}.`, input: raw },
      ]);
      captureRejectedIntent(buildRejection({ model: this.model, finishReason, error: failure, rawContent: raw }));
      return { intent: unreadable(), usage: readUsage(json.usage), model: this.model, status: "unreadable" };
    }

    const parsed = ModelIntent.safeParse(normalize(parsedJson));

    // A rejected reply costs the same as an accepted one and tells the shopper
    // nothing. Under the private test's diagnostics flag, record why.
    if (!parsed.success) {
      captureRejectedIntent(buildRejection({ model: this.model, finishReason, error: parsed.error, rawContent: raw }));
      return { intent: unreadable(), usage: readUsage(json.usage), model: this.model, status: "unreadable" };
    }

    // An empty reply is not an answer. It is what a truncated or hollow payload
    // looks like once the schema's defaults have filled it in, and it reached
    // the shopper as a blank message rather than a rejection.
    if (parsed.data.reply.trim() === "") {
      const failure = new z.ZodError([
        { code: "custom", path: ["reply"], message: `The reply was empty. finish_reason=${finishReason ?? "unknown"}.`, input: raw },
      ]);
      captureRejectedIntent(buildRejection({ model: this.model, finishReason, error: failure, rawContent: raw }));
      return { intent: unreadable(), usage: readUsage(json.usage), model: this.model, status: "unreadable" };
    }

    return {
      intent: parsed.data,
      // Missing or nonsensical usage is not zero usage. Reporting it as null
      // makes the caller hold the reservation instead of releasing it.
      usage: readUsage(json.usage),
      model: this.model,
      status: "ok",
    };
  }
}

function isOpenAiHost(baseUrl: string): boolean {
  try {
    const u = new URL(baseUrl);
    return u.protocol === "https:" && u.hostname.toLowerCase() === OPENAI_HOST;
  } catch {
    return false;
  }
}

function readUsage(u: { prompt_tokens?: number; completion_tokens?: number } | undefined): TokenUsage | null {
  if (!u) return null;
  const inputTokens = u.prompt_tokens;
  const outputTokens = u.completion_tokens;
  const usable = (n: unknown): n is number => typeof n === "number" && Number.isFinite(n) && n >= 0;
  if (!usable(inputTokens) || !usable(outputTokens)) return null;
  // A 200 that reports no tokens at all did not happen. Treat it as unknown.
  if (inputTokens === 0 && outputTokens === 0) return null;
  return { inputTokens, outputTokens };
}

// A status code is only evidence of "not billed" when the provider itself
// rejected the request. An OpenAI error body carries an `error` object; a 4xx
// from an intermediary in front of it does not, and gives us no such evidence.
async function statusError(res: Response): Promise<ProviderCallError> {
  if (res.status < 400 || res.status >= 500) return new ProviderCallError(`The provider returned ${res.status}.`, "uncertain");
  let looksLikeProvider = false;
  try {
    const body = (await res.json()) as { error?: unknown };
    looksLikeProvider = typeof body?.error === "object" && body.error !== null;
  } catch {
    looksLikeProvider = false;
  }
  // 408 and 499 mean the request was cut off, not refused, so they stay uncertain.
  const refusedBeforeInference = looksLikeProvider && res.status !== 408 && res.status !== 499;
  return new ProviderCallError(`The provider returned ${res.status}.`, refusedBeforeInference ? "not_billed" : "uncertain");
}

// Only a failure that provably happened before the request was written settles
// at zero: a name that did not resolve, a connection that was refused. Anything
// after that, including an abort, may have been processed and charged.
function connectionError(e: unknown, phase: "before" | "after"): ProviderCallError {
  const message = e instanceof Error ? e.message : String(e);
  const aborted = e instanceof Error && (e.name === "AbortError" || e.name === "TimeoutError" || /abort/i.test(message));
  if (phase === "before") {
    const neverSent = /ENOTFOUND|ECONNREFUSED|EAI_AGAIN|getaddrinfo|ERR_SSL|CERT_/i.test(message);
    if (neverSent && !aborted) return new ProviderCallError("The assistant could not be reached.", "not_billed");
  }
  return new ProviderCallError(aborted ? "The request timed out." : "The request could not be completed.", "uncertain");
}

// The model returns JSON but not necessarily our JSON. Coerce the shapes we
// tolerate, then let Zod reject the rest.
// What the shopper gets when nothing usable came back. Named once so every
// path that gives up returns the same thing and none of them can be mistaken
// for a successful empty answer.
export const UNREADABLE_REPLY = "I could not read that reliably. Could you say it another way?";

function unreadable(): ModelIntent {
  return { reply: UNREADABLE_REPLY, hard: [], soft: [], unmapped: [], medicalIntent: false, suggestCompare: [] };
}

// The shape the model is asked for, expressed as JSON Schema for OpenAI's
// strict structured outputs.
//
// Strict mode is constrained decoding, not advice, and it rejects a schema it
// cannot compile. The constraints it imposes are narrower than JSON Schema:
//
//   - every object needs `additionalProperties: false`;
//   - every property must appear in `required`, so an optional field is
//     expressed by allowing null rather than by leaving it out.
//
// Size and length keywords are a separate matter, and the blanket claim that
// they are unsupported was wrong: OpenAI documents additional restrictions for
// fine-tuned models, so support is not uniform across models and no single
// statement covers it. This schema declines to use them anyway, because it
// costs nothing to: `ModelIntent` enforces every count and range on every
// reply, whatever response_format was sent.
//
// So this schema carries the shape and the closed enumerations, which is what
// the model kept getting wrong, and the counts and ranges stay in Zod.
//
// IMPORTANT: the official documentation could not be read from this container
// (platform.openai.com and developers.openai.com are both blocked by the egress
// policy), so the rules above come from secondary sources. See
// docs/ASSISTANT.md for what that means and what remains unverified.
const MONEY_BRANCH = {
  type: "object",
  properties: { amount: { type: "number" }, currency: { type: "string", enum: [MONEY_CURRENCY] } },
  required: ["amount", "currency"],
  additionalProperties: false,
};

// A hard constraint's value, matching ModelHardConstraint exactly. `null` is
// how strict mode expresses "no value here", because every property must be
// present; `normalize` turns it back into an absent field before validation.
const HARD_VALUE = {
  anyOf: [
    MONEY_BRANCH,
    { type: "number" },
    { type: "string" },
    { type: "boolean" },
    { type: "array", items: { type: "string" } },
    { type: "array", items: { type: "number" } },
    { type: "null" },
  ],
};

// A soft preference's value, matching ModelSoftPreference exactly. It has no
// numeric-array branch, and neither does this: offering the model a shape the
// validator refuses is how a reply gets discarded for following instructions.
const SOFT_VALUE = {
  anyOf: [MONEY_BRANCH, { type: "number" }, { type: "string" }, { type: "boolean" }, { type: "array", items: { type: "string" } }, { type: "null" }],
};

export function intentJsonSchema(): Record<string, unknown> {
  return {
    type: "object",
    properties: {
      reply: { type: "string" },
      hard: {
        type: "array",
        items: {
          type: "object",
          properties: { key: { type: "string" }, op: { type: "string", enum: [...CONDITION_OPS] }, value: HARD_VALUE },
          required: ["key", "op", "value"],
          additionalProperties: false,
        },
      },
      soft: {
        type: "array",
        items: {
          type: "object",
          properties: {
            key: { type: "string" },
            direction: { type: "string", enum: [...SOFT_DIRECTIONS] },
            value: SOFT_VALUE,
            weight: { type: "number" },
          },
          required: ["key", "direction", "value", "weight"],
          additionalProperties: false,
        },
      },
      unmapped: { type: "array", items: { type: "string" } },
      medicalIntent: { type: "boolean" },
      suggestCompare: { type: "array", items: { type: "string" } },
    },
    required: ["reply", "hard", "soft", "unmapped", "medicalIntent", "suggestCompare"],
    additionalProperties: false,
  };
}

// Keywords this schema declines to use. Not a claim about what the API rejects:
// support varies by model and fine-tuned models carry further restrictions.
// Exported so a test can walk the schema and fail if one is reintroduced,
// because a schema strict mode will not compile is a 400 before inference.
export const STRICT_UNSUPPORTED_KEYWORDS = ["maxItems", "minItems", "minLength", "maxLength", "minimum", "maximum", "pattern", "format", "default"];

// Unchanged unless an operator opts in, because the capability is unverified
// against this account.
export function responseFormat(env: NodeJS.ProcessEnv = process.env): Record<string, unknown> {
  if (env.ASSISTANT_RESPONSE_FORMAT?.trim() === "json_schema") {
    return { type: "json_schema", json_schema: { name: "model_intent", strict: true, schema: intentJsonSchema() } };
  }
  return { type: "json_object" };
}

function normalize(v: unknown): unknown {
  if (typeof v !== "object" || v === null) return {};
  const o = { ...(v as Record<string, unknown>) };
  if (o.question === null) delete o.question;
  if (o.question && typeof o.question === "object") {
    const q = o.question as Record<string, unknown>;
    if (!Array.isArray(q.options)) q.options = [];
  }
  for (const k of ["hard", "soft", "unmapped", "suggestCompare"]) if (!Array.isArray(o[k])) o[k] = [];

  // Strict structured outputs cannot omit a property: every one must be
  // present, so "no value" arrives as `value: null`. The validator accepts an
  // absent value, not a null one, so a null is turned back into an absence
  // here. Without this, every preference with no target value would be
  // rejected the moment the schema was switched on, which is precisely the
  // shape of reply the schema exists to make more reliable.
  const dropNullValue = (entry: Record<string, unknown>) => {
    if (entry.value !== null) return entry;
    const rest = { ...entry };
    delete rest.value;
    return rest;
  };
  if (Array.isArray(o.hard)) {
    o.hard = (o.hard as Record<string, unknown>[]).map((h) => (h && typeof h === "object" ? dropNullValue(h) : h));
  }
  if (Array.isArray(o.soft)) {
    o.soft = (o.soft as Record<string, unknown>[]).map((s) => (s && typeof s === "object" ? dropNullValue({ weight: 0.5, direction: "prefer_high", ...s }) : s));
  }
  if (typeof o.reply !== "string") o.reply = "";
  return o;
}

export const ScriptedIntent = z.object({ reply: z.string() });
