import { CategoryDefinition } from "../category";

export const coldPlunge = CategoryDefinition.parse({
  id: "cold-plunge",
  slug: "cold-plunge",
  name: "Cold Plunges",
  navLabel: "Cold Plunge",
  tagline: "Tubs and chillers compared by temperature control, setup and size.",
  intro:
    "The biggest split in cold plunges is whether a chiller is included. Everything else is size, insulation, sanitation and where you can put the thing. We lay those out side by side.",
  images: [
    { id: "cold-plunge-hero", kind: "demo_placeholder", role: "primary", src: "demo:cold-plunge-hero", alt: "Cold plunge tub on a patio at dawn, demo image" },
  ],
  subcategories: [
    { id: "tub-with-chiller", label: "Tub with chiller" },
    { id: "tub-only", label: "Tub only" },
    { id: "inflatable", label: "Inflatable" },
  ],
  attributeDefinitions: [
    {
      key: "chiller_included",
      label: "Chiller included",
      type: "boolean",
      group: "Temperature",
      compareOrder: 10,
      filterable: true,
      preferenceDirection: "higher_better",
      required: true,
      showOnCard: true,
    },
    {
      key: "min_temp_f",
      label: "Lowest temperature (manufacturer reported)",
      shortLabel: "Lowest temp",
      type: "number",
      unit: "°F",
      group: "Temperature",
      compareOrder: 20,
      preferenceDirection: "lower_better",
      alwaysShowVerification: true,
      showOnCard: true,
    },
    {
      key: "heating",
      label: "Heating mode",
      type: "boolean",
      group: "Temperature",
      compareOrder: 30,
    },
    {
      key: "tub_type",
      label: "Tub type",
      type: "enum",
      enumOptions: [
        { value: "barrel", label: "Upright barrel" },
        { value: "tub", label: "Reclined tub" },
        { value: "inflatable", label: "Inflatable" },
      ],
      group: "Form",
      compareOrder: 40,
      filterable: true,
      required: true,
    },
    {
      key: "water_capacity_gal",
      label: "Water capacity",
      type: "number",
      unit: "gal",
      group: "Form",
      compareOrder: 50,
    },
    {
      key: "fits_height_in",
      label: "Fits users up to",
      type: "number",
      unit: "in",
      group: "Form",
      compareOrder: 60,
      preferenceDirection: "higher_better",
    },
    {
      key: "insulated",
      label: "Insulated shell",
      type: "boolean",
      group: "Form",
      compareOrder: 70,
      preferenceDirection: "higher_better",
    },
    {
      key: "placement",
      label: "Placement",
      type: "list",
      group: "Setup",
      compareOrder: 80,
      filterable: true,
      tooltip: "Values: indoor, outdoor.",
    },
    {
      key: "plumbing",
      label: "Power and plumbing",
      type: "enum",
      enumOptions: [
        { value: "none", label: "None. Fill with a hose.", rank: 1 },
        { value: "plug_in_120v", label: "Standard 120V outlet", rank: 2 },
        { value: "dedicated_circuit", label: "Dedicated 120V circuit", rank: 3 },
      ],
      group: "Setup",
      compareOrder: 90,
      filterable: true,
      preferenceDirection: "lower_better",
    },
    {
      key: "sanitation_system",
      label: "Filtration or sanitation system",
      shortLabel: "Sanitation",
      type: "boolean",
      group: "Maintenance",
      compareOrder: 100,
      preferenceDirection: "higher_better",
      required: true,
    },
    {
      key: "sanitation_methods",
      label: "Sanitation methods",
      type: "list",
      group: "Maintenance",
      compareOrder: 101,
      tooltip: "Values: ozone, uv, filter.",
    },
    {
      key: "warranty_years",
      label: "Warranty",
      type: "number",
      unit: "yr",
      group: "Support",
      compareOrder: 110,
      preferenceDirection: "higher_better",
      required: true,
      showOnCard: true,
      scoreCap: 5,
      displayField: "warranty",
    },
  ],
  cardSpecKeys: ["chiller_included", "min_temp_f", "warranty_years"],
  compareGroups: [
    { label: "Temperature", keys: ["chiller_included", "min_temp_f", "heating"] },
    { label: "Form", keys: ["tub_type", "water_capacity_gal", "fits_height_in", "insulated"] },
    { label: "Setup", keys: ["placement", "plumbing"] },
    { label: "Maintenance", keys: ["sanitation_system", "sanitation_methods"] },
    { label: "Support", keys: ["warranty_years"] },
  ],
  filters: [
    {
      key: "price",
      label: "Price",
      kind: "range",
      presets: [
        { label: "Under $500", condition: { key: "price", op: "lt", value: 50000 } },
        { label: "Under $2,000", condition: { key: "price", op: "lt", value: 200000 } },
        { label: "Under $5,000", condition: { key: "price", op: "lt", value: 500000 } },
      ],
    },
    { key: "chiller_included", label: "Chiller included", kind: "boolean" },
    { key: "tub_type", label: "Tub type", kind: "enum" },
    { key: "placement", label: "Placement", kind: "list" },
    { key: "plumbing", label: "Power", kind: "enum" },
  ],
  scoring: {
    criteria: [
      { key: "chiller_included", weight: 3 },
      { key: "insulated", weight: 1.5 },
      { key: "sanitation_system", weight: 1.5 },
      { key: "warranty_years", weight: 1.5 },
      { key: "min_temp_f", weight: 1 },
      { key: "fits_height_in", weight: 0.5 },
    ],
    completenessFloor: 0.75,
  },
  // 0.50 / 0.50 by review decision: at 0.65 / 0.35 a $9,599 tub won Best Value.
  // Revisit with verified products.
  value: { qualityWeight: 0.5, affordabilityWeight: 0.5, priceBasis: "price" },
  badges: {
    priceBasis: "price",
    budgetMaxMinor: 150000,
    premiumMinMinor: 500000,
    minQualifying: 2,
    tieBreak: ["warranty_years", "fits_height_in"],
  },
  insightRules: [
    { id: "chiller", when: [{ key: "chiller_included", op: "eq", value: true }], text: "Chiller included. Set a temperature and hold it.", tone: "strength" },
    { id: "no-chiller", when: [{ key: "chiller_included", op: "eq", value: false }], text: "No chiller. You add ice or buy a chiller separately.", tone: "tradeoff" },
    { id: "heating", when: [{ key: "heating", op: "eq", value: true }], text: "Heats as well as cools.", tone: "neutral" },
    { id: "inflatable", when: [{ key: "tub_type", op: "eq", value: "inflatable" }], text: "Inflatable shell. Light, packable, quick to set up.", tone: "neutral" },
    { id: "dedicated", when: [{ key: "plumbing", op: "eq", value: "dedicated_circuit" }], text: "Needs a dedicated 120V circuit.", tone: "tradeoff" },
    { id: "insulated", when: [{ key: "insulated", op: "eq", value: true }], text: "Insulated shell holds temperature longer between sessions.", tone: "strength" },
    { id: "sanitation", when: [{ key: "sanitation_system", op: "eq", value: true }], text: "Built-in sanitation: {sanitation_methods}.", tone: "strength" },
    { id: "manual-water", when: [{ key: "sanitation_system", op: "eq", value: false }], text: "No filtration. Plan on regular water changes.", tone: "tradeoff" },
    { id: "warranty-long", when: [{ key: "warranty_years", op: "gte", value: 3 }], text: "{warranty}", tone: "strength" },
    { id: "warranty-short", when: [{ key: "warranty_years", op: "lte", value: 1 }], text: "Short warranty: {warranty}", tone: "tradeoff" },
    { id: "under-500", when: [{ key: "price", op: "lt", value: 50000 }], text: "Under $500.", tone: "strength" },
  ],
  relaxationOrder: ["price", "chiller_included", "tub_type", "placement"],
  priceTiers: [
    { id: "budget", label: "Under $1,500", maxMinor: 150000 },
    { id: "mid", label: "$1,500 to $5,000", maxMinor: 500000 },
    { id: "premium", label: "Over $5,000" },
  ],
  facets: [
    { slug: "with-chiller", label: "With a chiller", title: "Cold Plunges With a Chiller", description: "Systems with an included chiller and temperature control.", conditions: [{ key: "chiller_included", op: "eq", value: true }] },
    { slug: "under-2000", label: "Under $2,000", title: "Cold Plunges Under $2,000", description: "Tubs and inflatables priced under $2,000.", conditions: [{ key: "price", op: "lt", value: 200000 }] },
    { slug: "under-5000", label: "Under $5,000", title: "Cold Plunges Under $5,000", description: "Mid-range systems priced under $5,000.", conditions: [{ key: "price", op: "lt", value: 500000 }] },
    { slug: "indoor", label: "Indoor", title: "Indoor Cold Plunges", description: "Rated by the manufacturer for indoor placement.", conditions: [{ key: "placement", op: "includes", value: "indoor" }] },
  ],
  matcherVocabulary: {
    chiller_included: {
      true: ["chiller", "hold temperature", "set the temperature", "no ice", "without ice", "keeps it cold"],
      false: ["no chiller", "use ice", "ice only"],
    },
    tub_type: {
      inflatable: ["inflatable", "portable", "pack up"],
      barrel: ["barrel", "upright", "standing"],
      tub: ["lie down", "recline", "reclined", "tub"],
    },
    placement: {
      indoor: ["indoor", "inside", "apartment", "garage", "basement", "bathroom"],
      outdoor: ["outdoor", "backyard", "patio", "deck"],
    },
  },
});
