import { CategoryDefinition } from "../category";

export const redLight = CategoryDefinition.parse({
  id: "red-light",
  slug: "red-light",
  name: "Red Light Therapy",
  navLabel: "Red Light",
  tagline: "Panels compared by coverage, output, size and warranty.",
  intro:
    "Red light panels differ mostly in how much of you they cover, how much light they put out, and how much room they take. We compare manufacturer-stated specs side by side and mark which numbers are reported versus verified.",
  images: [
    { id: "red-light-hero", kind: "demo_placeholder", role: "primary", src: "demo:red-light-hero", alt: "Warm red light panel in a living room, demo image" },
  ],
  subcategories: [
    { id: "panel", label: "Panels" },
    { id: "handheld", label: "Handheld" },
  ],
  attributeDefinitions: [
    {
      key: "coverage",
      label: "Coverage",
      type: "enum",
      enumOptions: [
        { value: "targeted", label: "Targeted", rank: 1 },
        { value: "half_body", label: "Half body", rank: 2 },
        { value: "full_body", label: "Full body", rank: 3 },
      ],
      group: "Coverage",
      compareOrder: 10,
      filterable: true,
      preferenceDirection: "higher_better",
      required: true,
      showOnCard: true,
      tooltip: "Editorial class based on panel height: targeted under 20 in, half body 20 to 34 in, full body 35 in and up.",
    },
    {
      key: "footprint",
      label: "Footprint",
      type: "enum",
      enumOptions: [
        { value: "compact", label: "Compact", rank: 1 },
        { value: "standard", label: "Standard", rank: 2 },
        { value: "large", label: "Large", rank: 3 },
      ],
      group: "Size",
      compareOrder: 20,
      filterable: true,
      preferenceDirection: "lower_better",
      required: true,
      tooltip: "Editorial class based on longest side: compact under 20 in, standard 20 to 40 in, large over 40 in.",
    },
    {
      key: "wavelengths_nm",
      label: "Wavelengths",
      shortLabel: "Wavelengths",
      type: "number_list",
      unit: "nm",
      group: "Light output",
      compareOrder: 30,
      required: true,
      showOnCard: true,
    },
    {
      key: "irradiance_mw_cm2",
      label: "Irradiance (manufacturer reported)",
      shortLabel: "Irradiance",
      type: "number",
      unit: "mW/cm²",
      group: "Light output",
      compareOrder: 40,
      preferenceDirection: "higher_better",
      alwaysShowVerification: true,
      tooltip: "Manufacturer-reported figure at the stated distance. Measurement methods differ across brands. Not comparable with precision.",
    },
    {
      key: "irradiance_distance_in",
      label: "Irradiance measured at",
      shortLabel: "At distance",
      type: "number",
      unit: "in",
      group: "Light output",
      compareOrder: 41,
    },
    {
      key: "led_count",
      label: "LED count",
      type: "integer",
      group: "Light output",
      compareOrder: 50,
      preferenceDirection: "higher_better",
    },
    {
      key: "power_w",
      label: "Power draw",
      type: "number",
      unit: "W",
      group: "Light output",
      compareOrder: 60,
    },
    {
      key: "mounting",
      label: "Mounting options",
      type: "list",
      group: "Setup",
      compareOrder: 70,
      filterable: true,
      tooltip: "Values: stand, door_hang, wall, tabletop, floor_stand_optional.",
    },
    {
      key: "app_control",
      label: "App control",
      type: "boolean",
      group: "Setup",
      compareOrder: 80,
    },
    {
      key: "pulsing",
      label: "Pulsing modes",
      type: "boolean",
      group: "Setup",
      compareOrder: 81,
    },
    {
      key: "warranty_years",
      label: "Warranty",
      type: "number",
      unit: "yr",
      group: "Support",
      compareOrder: 90,
      preferenceDirection: "higher_better",
      required: true,
      showOnCard: true,
    },
    {
      key: "return_window_days",
      label: "Return window",
      type: "integer",
      unit: "days",
      group: "Support",
      compareOrder: 91,
      preferenceDirection: "higher_better",
    },
  ],
  cardSpecKeys: ["coverage", "wavelengths_nm", "warranty_years"],
  compareGroups: [
    { label: "Coverage and size", keys: ["coverage", "footprint"] },
    { label: "Light output", keys: ["wavelengths_nm", "irradiance_mw_cm2", "irradiance_distance_in", "led_count", "power_w"] },
    { label: "Setup", keys: ["mounting", "app_control", "pulsing"] },
    { label: "Support", keys: ["warranty_years", "return_window_days"] },
  ],
  filters: [
    {
      key: "price",
      label: "Price",
      kind: "range",
      presets: [
        { label: "Under $300", condition: { key: "price", op: "lt", value: 30000 } },
        { label: "Under $500", condition: { key: "price", op: "lt", value: 50000 } },
        { label: "Under $1,000", condition: { key: "price", op: "lt", value: 100000 } },
      ],
    },
    { key: "coverage", label: "Coverage", kind: "enum" },
    { key: "footprint", label: "Footprint", kind: "enum" },
    { key: "mounting", label: "Mounting", kind: "list" },
  ],
  scoring: {
    // Irradiance is manufacturer-reported and measured inconsistently across
    // brands, so its weight stays low despite being the headline spec.
    criteria: [
      { key: "coverage", weight: 3 },
      { key: "irradiance_mw_cm2", weight: 1 },
      { key: "led_count", weight: 1 },
      { key: "warranty_years", weight: 1.5 },
      { key: "return_window_days", weight: 0.5 },
    ],
    completenessFloor: 0.75,
  },
  value: { qualityWeight: 1, priceWeight: 1, priceScale: "log", priceBasis: "price", minScoreShare: 0.5 },
  badges: {
    priceBasis: "price",
    budgetMaxMinor: 40000,
    premiumMinMinor: 100000,
    minQualifying: 2,
    tieBreak: ["warranty_years", "led_count"],
  },
  insightRules: [
    { id: "compact", when: [{ key: "footprint", op: "eq", value: "compact" }], text: "Fits a small space. Longest side under 20 in.", tone: "strength" },
    { id: "large", when: [{ key: "footprint", op: "eq", value: "large" }], text: "Large panel. Plan for a door or wall mount and clear floor space.", tone: "tradeoff" },
    { id: "full", when: [{ key: "coverage", op: "eq", value: "full_body" }], text: "Full-body coverage from one panel.", tone: "strength" },
    { id: "targeted", when: [{ key: "coverage", op: "eq", value: "targeted" }], text: "Targeted coverage. Full-body sessions mean repositioning.", tone: "tradeoff" },
    { id: "warranty-long", when: [{ key: "warranty_years", op: "gte", value: 3 }], text: "{warranty_years} warranty.", tone: "strength" },
    { id: "warranty-short", when: [{ key: "warranty_years", op: "lte", value: 1 }], text: "Warranty limited to {warranty_years}.", tone: "tradeoff" },
    { id: "app", when: [{ key: "app_control", op: "eq", value: true }], text: "App control included.", tone: "neutral" },
    { id: "irradiance-at", when: [{ key: "irradiance_mw_cm2", op: "exists" }, { key: "irradiance_distance_in", op: "exists" }], text: "Manufacturer reports {irradiance_mw_cm2} at {irradiance_distance_in}. Not independently verified here.", tone: "neutral" },
    { id: "irradiance-no-distance", when: [{ key: "irradiance_mw_cm2", op: "exists" }, { key: "irradiance_distance_in", op: "missing" }], text: "Manufacturer reports {irradiance_mw_cm2}. Measurement distance not stated. Not independently verified here.", tone: "neutral" },
    { id: "under-300", when: [{ key: "price", op: "lt", value: 30000 }], text: "Under $300.", tone: "strength" },
  ],
  relaxationOrder: ["price", "coverage", "footprint"],
  priceTiers: [
    { id: "budget", label: "Under $400", maxMinor: 40000 },
    { id: "mid", label: "$400 to $1,000", maxMinor: 100000 },
    { id: "premium", label: "Over $1,000" },
  ],
  facets: [
    { slug: "full-body", title: "Full-Body Red Light Panels", description: "Panels 35 inches and taller, sized for standing sessions.", conditions: [{ key: "coverage", op: "eq", value: "full_body" }] },
    { slug: "targeted", title: "Targeted Red Light Panels", description: "Compact panels for face, joints and desk use.", conditions: [{ key: "coverage", op: "eq", value: "targeted" }] },
    { slug: "under-500", title: "Red Light Panels Under $500", description: "Every panel we track priced under $500.", conditions: [{ key: "price", op: "lt", value: 50000 }] },
    { slug: "under-1000", title: "Red Light Panels Under $1,000", description: "Mid-range panels priced under $1,000.", conditions: [{ key: "price", op: "lt", value: 100000 }] },
  ],
  matcherVocabulary: {
    coverage: {
      full_body: ["full body", "full-body", "whole body", "head to toe", "entire body"],
      half_body: ["half body", "half-body", "torso", "upper body"],
      targeted: ["face", "targeted", "spot", "small area", "knee", "hand", "desk", "travel"],
    },
    footprint: {
      compact: ["small space", "apartment", "compact", "take over", "portable", "small room", "dorm"],
    },
    mounting: {
      door_hang: ["door", "hang on a door"],
      stand: ["stand", "floor stand"],
      tabletop: ["tabletop", "desk"],
    },
  },
});
