import { CategoryDefinition } from "../category";

export const wellnessDrinks = CategoryDefinition.parse({
  id: "wellness-drinks",
  slug: "wellness-drinks",
  name: "Wellness Drinks",
  navLabel: "Wellness Drinks",
  tagline: "Electrolytes, greens, energy and prebiotic sodas compared by label, not marketing.",
  intro:
    "Functional drinks compete on labels: sugar, caffeine, sodium, serving cost. We normalize those numbers per serving so a stick pack, a scoop and a can compare on the same terms.",
  images: [
    { id: "wellness-drinks-hero", kind: "demo_placeholder", role: "primary", src: "demo:wellness-drinks-hero", alt: "Glass of electrolyte drink on a kitchen counter, demo image" },
  ],
  subcategories: [
    { id: "electrolytes", label: "Electrolytes" },
    { id: "greens", label: "Greens" },
    { id: "energy", label: "Energy" },
    { id: "prebiotic-soda", label: "Prebiotic soda" },
  ],
  attributeDefinitions: [
    {
      key: "function",
      label: "Function",
      type: "list",
      group: "Basics",
      compareOrder: 10,
      filterable: true,
      required: true,
      showOnCard: true,
      tooltip: "Values: electrolytes, greens, energy, prebiotic, hydration.",
    },
    {
      key: "format",
      label: "Format",
      type: "enum",
      enumOptions: [
        { value: "powder_stick", label: "Powder stick pack" },
        { value: "powder_scoop", label: "Powder, scoop" },
        { value: "rtd_can", label: "Ready to drink can" },
      ],
      group: "Basics",
      compareOrder: 20,
      filterable: true,
      required: true,
    },
    {
      key: "serving_size",
      label: "Serving size",
      type: "string",
      group: "Basics",
      compareOrder: 30,
      required: true,
    },
    {
      key: "servings_per_pack",
      label: "Servings per pack",
      type: "integer",
      group: "Basics",
      compareOrder: 40,
      required: true,
    },
    {
      key: "price_per_serving_minor",
      label: "Price per serving",
      type: "integer",
      unit: "USD_minor",
      group: "Basics",
      compareOrder: 50,
      preferenceDirection: "lower_better",
      required: true,
      showOnCard: true,
      tooltip: "Editorial calculation: current pack price divided by servings per pack.",
    },
    {
      key: "sugar_g",
      label: "Total sugar",
      type: "number",
      unit: "g",
      group: "Nutrition",
      compareOrder: 60,
      filterable: true,
      preferenceDirection: "lower_better",
      required: true,
      showOnCard: true,
    },
    {
      key: "added_sugar_g",
      label: "Added sugar",
      type: "number",
      unit: "g",
      group: "Nutrition",
      compareOrder: 61,
      preferenceDirection: "lower_better",
    },
    {
      key: "calories",
      label: "Calories",
      type: "number",
      unit: "kcal",
      group: "Nutrition",
      compareOrder: 70,
      preferenceDirection: "lower_better",
    },
    {
      key: "caffeine_mg",
      label: "Caffeine",
      type: "number",
      unit: "mg",
      group: "Nutrition",
      compareOrder: 80,
      filterable: true,
      required: true,
    },
    {
      key: "sodium_mg",
      label: "Sodium",
      type: "number",
      unit: "mg",
      group: "Electrolytes",
      compareOrder: 90,
    },
    {
      key: "potassium_mg",
      label: "Potassium",
      type: "number",
      unit: "mg",
      group: "Electrolytes",
      compareOrder: 91,
    },
    {
      key: "magnesium_mg",
      label: "Magnesium",
      type: "number",
      unit: "mg",
      group: "Electrolytes",
      compareOrder: 92,
    },
    {
      key: "fiber_g",
      label: "Fiber",
      type: "number",
      unit: "g",
      group: "Nutrition",
      compareOrder: 93,
    },
    {
      key: "sweeteners",
      label: "Sweeteners",
      type: "list",
      group: "Ingredients",
      compareOrder: 100,
      tooltip: "Values: stevia, monk_fruit, cane_sugar, cassava_root_syrup, dextrose, allulose, fruit_juice, none.",
    },
    {
      key: "dietary",
      label: "Dietary",
      type: "list",
      group: "Ingredients",
      compareOrder: 110,
      tooltip: "Values: vegan, gluten_free, keto, non_gmo, paleo.",
    },
    {
      key: "subscription_available",
      label: "Subscription",
      type: "boolean",
      group: "Buying",
      compareOrder: 120,
      filterable: true,
      preferenceDirection: "higher_better",
    },
    {
      key: "subscription_discount_pct",
      label: "Subscription discount",
      type: "number",
      unit: "%",
      group: "Buying",
      compareOrder: 121,
    },
  ],
  cardSpecKeys: ["function", "price_per_serving_minor", "sugar_g"],
  compareGroups: [
    { label: "Basics", keys: ["function", "format", "serving_size", "servings_per_pack", "price_per_serving_minor"] },
    { label: "Nutrition", keys: ["sugar_g", "added_sugar_g", "calories", "caffeine_mg", "fiber_g"] },
    { label: "Electrolytes", keys: ["sodium_mg", "potassium_mg", "magnesium_mg"] },
    { label: "Ingredients", keys: ["sweeteners", "dietary"] },
    { label: "Buying", keys: ["subscription_available", "subscription_discount_pct"] },
  ],
  filters: [
    {
      key: "price_per_serving_minor",
      label: "Per serving",
      kind: "range",
      presets: [
        { label: "Under $1", condition: { key: "price_per_serving_minor", op: "lt", value: 100 } },
        { label: "Under $2", condition: { key: "price_per_serving_minor", op: "lt", value: 200 } },
      ],
    },
    { key: "function", label: "Function", kind: "list" },
    { key: "format", label: "Format", kind: "enum" },
    {
      key: "sugar_g",
      label: "Sugar",
      kind: "range",
      presets: [{ label: "Zero sugar", condition: { key: "sugar_g", op: "eq", value: 0 } }],
    },
    {
      key: "caffeine_mg",
      label: "Caffeine",
      kind: "range",
      presets: [{ label: "Caffeine free", condition: { key: "caffeine_mg", op: "eq", value: 0 } }],
    },
    { key: "subscription_available", label: "Subscription", kind: "boolean" },
  ],
  scoring: {
    criteria: [
      { key: "sugar_g", weight: 2 },
      { key: "added_sugar_g", weight: 1 },
      { key: "calories", weight: 0.5 },
      { key: "subscription_available", weight: 0.5 },
    ],
    label: "Label score",
    meaning:
      "How the nutrition label reads against our criteria: less sugar and fewer calories score higher. It says nothing about taste, ingredient quality or whether the formula suits you.",
    segmentKey: "function",
    completenessFloor: 0.75,
  },
  value: { qualityWeight: 0.65, affordabilityWeight: 0.35, priceBasis: "attribute:price_per_serving_minor" },
  badges: {
    priceBasis: "attribute:price_per_serving_minor",
    budgetMaxMinor: 100,
    premiumMinMinor: 250,
    minQualifying: 2,
    tieBreak: ["sugar_g", "calories"],
  },
  insightRules: [
    { id: "zero-sugar", when: [{ key: "sugar_g", op: "eq", value: 0 }], text: "Zero sugar.", tone: "strength" },
    { id: "high-sugar", when: [{ key: "sugar_g", op: "gte", value: 10 }], text: "{sugar_g} sugar per serving.", tone: "tradeoff" },
    { id: "high-caffeine", when: [{ key: "caffeine_mg", op: "gte", value: 150 }], text: "High caffeine: {caffeine_mg} per serving.", tone: "neutral" },
    { id: "caffeine-free", when: [{ key: "caffeine_mg", op: "eq", value: 0 }], text: "Caffeine free.", tone: "neutral" },
    { id: "high-sodium", when: [{ key: "sodium_mg", op: "gte", value: 800 }], text: "High-sodium formula: {sodium_mg} per serving.", tone: "neutral" },
    { id: "cheap-serving", when: [{ key: "price_per_serving_minor", op: "lte", value: 100 }], text: "Under $1 per serving.", tone: "strength" },
    { id: "pricey-serving", when: [{ key: "price_per_serving_minor", op: "gte", value: 250 }], text: "Over $2.50 per serving.", tone: "tradeoff" },
    { id: "subscription-discount", when: [{ key: "subscription_available", op: "eq", value: true }, { key: "subscription_discount_pct", op: "exists" }], text: "Subscription available, {subscription_discount_pct} off.", tone: "neutral" },
    { id: "subscription", when: [{ key: "subscription_available", op: "eq", value: true }, { key: "subscription_discount_pct", op: "missing" }], text: "Subscription available.", tone: "neutral" },
    { id: "fiber", when: [{ key: "fiber_g", op: "gte", value: 5 }], text: "{fiber_g} fiber per serving.", tone: "strength" },
  ],
  relaxationOrder: ["price_per_serving_minor", "sugar_g", "caffeine_mg", "function"],
  priceTiers: [
    { id: "budget", label: "Under $1 per serving", maxMinor: 100 },
    { id: "mid", label: "$1 to $2.50 per serving", maxMinor: 250 },
    { id: "premium", label: "Over $2.50 per serving" },
  ],
  facets: [
    { slug: "electrolytes", label: "Electrolytes", title: "Electrolyte Drinks", description: "Electrolyte mixes compared by sodium, sugar and cost per serving.", conditions: [{ key: "function", op: "includes", value: "electrolytes" }] },
    { slug: "greens", label: "Greens", title: "Greens Powders", description: "Daily greens compared by serving cost and label.", conditions: [{ key: "function", op: "includes", value: "greens" }] },
    { slug: "energy", label: "Energy", title: "Energy Drinks", description: "Caffeinated functional drinks compared by caffeine, sugar and cost.", conditions: [{ key: "function", op: "includes", value: "energy" }] },
    { slug: "sugar-free", label: "Sugar-free", title: "Sugar-Free Wellness Drinks", description: "Zero-sugar options across every function.", conditions: [{ key: "sugar_g", op: "eq", value: 0 }] },
  ],
  aliases: [
    "wellness drink",
    "wellness drinks",
    "drink mix",
    "drink mixes",
    "electrolyte drink",
    "electrolyte drinks",
    "electrolyte powder",
    "greens powder",
    "greens powders",
    "hydration drink",
    "hydration powder",
    "energy drink",
    "energy drinks",
  ],
  matcherVocabulary: {
    function: {
      electrolytes: ["electrolyte", "electrolytes", "hydration", "sweat", "salt", "cramps"],
      greens: ["greens", "vitamins", "daily nutrition", "multivitamin"],
      energy: ["energy", "caffeine", "pick me up", "pre workout", "pre-workout"],
      prebiotic: ["soda", "gut", "prebiotic", "fiber", "digestion"],
    },
    format: {
      rtd_can: ["can", "cans", "ready to drink", "grab and go"],
      powder_stick: ["stick", "packet", "sachet", "travel"],
    },
  },
});
