import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { categories, categoryById } from "@/domain/categories";
import type { CategoryDefinition } from "@/domain/category";
import { formatMoney } from "@/domain/money";
import type { Product } from "@/domain/product";
import { recommendCategory } from "@/domain/recommend";
import { toProductView, type ProductView } from "@/domain/view";
import { loadLocalCatalog } from "@/providers/catalog/LocalCatalogProvider";

// Regenerates docs/PARTNER-SHOWCASE-CHECKLIST.md from the catalogue.
//
// Every figure in that document is computed here, so it cannot drift from the
// data by being retyped. The judgement it carries is in the prose written into
// this file, not in numbers copied by hand.
//
//   npx tsx scripts/partner-checklist.ts

export const CHECKLIST_PATH = join(process.cwd(), "docs/PARTNER-SHOWCASE-CHECKLIST.md");

const cat = loadLocalCatalog(join(process.cwd(), "catalog"));
const viewOf = (p: Product): ProductView =>
  toProductView(p, { category: categoryById(p.categoryId)!, brands: cat.brands, merchants: cat.merchants });

type Tier = "hold" | "gaps" | "show";
const TIER_LABEL: Record<Tier, string> = {
  show: "Show it",
  gaps: "Show it, with the gaps named",
  hold: "Hold it back",
};

function tierOf(v: ProductView, eligible: boolean): { tier: Tier; because: string[] } {
  const because: string[] = [];
  if (v.price.isDemo) because.push("no confirmed price");
  if (!eligible) because.push("below the completeness floor, so it holds no badge");
  const demo = Object.entries(v.provenance).filter(([f, p]) => f.startsWith("attributes.") && p.verification === "demo");
  if (demo.length > 0) because.push(`${demo.length} specification${demo.length === 1 ? "" : "s"} are prototype data`);
  if (because.length > 0) return { tier: v.price.isDemo || !eligible ? "hold" : "gaps", because };
  const notStated = Object.entries(v.provenance).filter(([f, p]) => f.startsWith("attributes.") && p.verification === "not_stated");
  const unknown = Object.entries(v.provenance).filter(([f, p]) => f.startsWith("attributes.") && p.verification === "unknown");
  if (notStated.length > 0) because.push(`${notStated.length} specification${notStated.length === 1 ? "" : "s"} its source does not state`);
  if (unknown.length > 0) because.push(`${unknown.length} with no recorded source`);
  return { tier: because.length > 0 ? "gaps" : "show", because };
}

function attributeLines(p: Product, v: ProductView, c: CategoryDefinition): string[] {
  const out: string[] = [];
  for (const def of c.attributeDefinitions) {
    const sv = p.attributes[def.key];
    const spec = v.specs.find((s) => s.key === def.key);
    if (!sv) {
      out.push(`- \`${def.key}\`${def.required ? " (required)" : ""}: **absent from the record**`);
      continue;
    }
    const bits: string[] = [];
    if (sv.value === undefined) bits.push(`no value, recorded as \`${sv.verification}\``);
    else if (spec?.moneyWithheld) bits.push("withheld: computed from a price that is prototype data");
    else if (sv.verification === "demo") bits.push(`prototype value \`${JSON.stringify(sv.value)}\``);
    else if (sv.bound) bits.push(`bound: ${spec?.formatted}`);
    if (sv.verification === "unknown") bits.push("source not recorded");
    if (sv.source.method === "secondhand") bits.push("relayed, maker's page not fetched");
    if (bits.length > 0) out.push(`- \`${def.key}\`${def.required ? " (required)" : ""}: ${bits.join("; ")}`);
  }
  return out;
}

export function buildPartnerChecklist(): string {
const lines: string[] = [];
const push = (s = "") => lines.push(s);

push("# Partner showcase checklist");
push();
push("What a prospective affiliate partner would find on each of the 20 products,");
push("and what is missing before this site is worth showing them. Generated by");
push("`scripts/partner-checklist.ts`, so every figure comes from the catalogue");
push("rather than from a hand copy. Regenerate it after any catalogue change.");
push();
push("**No manufacturer page was fetched to produce this.** The environment's");
push("network policy blocks outbound HTTPS to anything but the model provider, so");
push("every source line below is what the repository records, not what a page said");
push("today. A recorded URL is a claim about where a figure came from; it is not");
push("verification that the figure is still right, and a search summary is not a");
push("visit. Where this file says a source was not fetched, that is a statement");
push("about this repository's evidence, not about the product.");
push();
push("Three verdicts, computed, not judged:");
push();
push("- **Show it.** A confirmed price, no prototype specifications, every");
push("  required specification present and sourced, and it holds its place in the");
push("  ranking on its own merits.");
push("- **Show it, with the gaps named.** A confirmed price and a place in the");
push("  ranking it earned, carrying specifications that are prototype data, or");
push("  whose source is unrecorded, or whose source states nothing. Every one of");
push("  those is marked on the page, and a partner will still ask about them.");
push("- **Hold it back.** No confirmed price, or below the completeness floor.");
push("  Either one invites the question the site cannot answer.");
push();
push("Two things apply to all 20 and are not repeated in each entry:");
push();
push("1. **Every image is a procedural placeholder.** There are no image files in");
push("   `public/`, no licence, no permission and nothing to show. A public image");
push("   URL is not permission and is not treated as any.");
push("2. **No affiliate relationship exists on any offer.** Every link is an");
push("   ordinary link to the maker or retailer, carrying");
push("   `rel=\"sponsored nofollow noopener\"` and no tracking parameter.");
push();

const counts: Record<Tier, string[]> = { show: [], gaps: [], hold: [] };

for (const c of categories) {
  const products = cat.products.filter((p) => p.categoryId === c.id);
  const views = products.map(viewOf);
  const ranked = recommendCategory(views, c);
  push(`## ${c.name}`);
  push();
  for (const p of products) {
    const v = viewOf(p);
    const item = ranked.products.find((x) => x.view.id === p.id)!;
    const { tier, because } = tierOf(v, item.eligible);
    counts[tier].push(`${v.brand.name} ${v.name}`);
    const badges = item.badges.length > 0 ? item.badges.join(", ") : "none";
    const sources = [...new Set(Object.values(v.provenance).map((pr) => pr.source.url).filter(Boolean))] as string[];
    const secondhand = Object.values(v.provenance).filter((pr) => pr.source.method === "secondhand").length;
    const total = Object.values(v.provenance).length;

    push(`### ${v.brand.name} ${v.name}`);
    push();
    const why = because.length > 0 ? `${because.join("; ")}.` : "";
    push(`**${TIER_LABEL[tier]}.**${why ? ` ${why.charAt(0).toUpperCase()}${why.slice(1)}` : ""}`);
    push();
    push("| | |");
    push("| --- | --- |");
    push(`| Record | \`${v.id}\`, \`/products/${v.slug}\` |`);
    push(
      `| Price | ${v.price.isDemo ? "**no confirmed price**; the page says to check the merchant" : `${formatMoney(v.price.money)}, ${v.price.basis === "reference" ? "reference price" : `lowest of ${v.price.offerCount} offer${v.price.offerCount === 1 ? "" : "s"}`}, checked ${v.price.checkedAt}`} |`,
    );
    push(
      `| Offers | ${v.offers.length === 0 ? "none" : v.offers.map((o) => `${o.merchant.name} (${o.priceIsDemo ? "prototype amount" : formatMoney(o.price)}, ${o.availability}, ${o.affiliateStatus === "unknown" ? "no affiliate relationship" : o.affiliateStatus})`).join("; ")} |`,
    );
    push(`| Links | ${v.offers.length === 0 ? "none" : v.offers.map((o) => o.url).join("<br>")} |`);
    push(`| Sources on file | ${sources.length === 0 ? "none" : sources.join("<br>")} |`);
    push(`| Retrieval | ${secondhand} of ${total} recorded fields were relayed rather than read from the source |`);
    push(`| Images | ${v.images.length} placeholder${v.images.length === 1 ? "" : "s"}, no rights evidence |`);
    push(`| Ranking | score ${item.score}, completeness ${Math.round(v.flags.completeness * 100)}%, badges: ${badges}${item.eligible ? "" : ", **ineligible**"} |`);
    push();
    const gaps = attributeLines(p, v, c);
    if (gaps.length > 0) {
      push("Specifications that are missing, unsupported or relayed:");
      push();
      for (const g of gaps) push(g);
      push();
    } else {
      push("Every specification carries a value and a source.");
      push();
    }
  }
}

// Per category, what a partner would see, and what it would take to fix it.
push("## What each category looks like to a partner");
push();
push("| Category | Products | Confirmed prices | Prototype specifications | Below the floor |");
push("| --- | --- | --- | --- | --- |");
for (const c of categories) {
  const views = cat.products.filter((p) => p.categoryId === c.id).map(viewOf);
  const ranked = recommendCategory(views, c);
  const priced = views.filter((v) => !v.price.isDemo).length;
  const demoSpecs = views.filter((v) => Object.entries(v.provenance).some(([f, pr]) => f.startsWith("attributes.") && pr.verification === "demo")).length;
  const short = ranked.products.filter((x) => !x.eligible).length;
  push(`| ${c.name} | ${views.length} | ${priced} of ${views.length} | ${demoSpecs} of ${views.length} carry some | ${short} |`);
}
push();

push("## Where that leaves the showcase");
push();
push(`**Show it: ${counts.show.length}.** ${counts.show.join(", ") || "None."}`);
push();
push(`**Show it, with the gaps named: ${counts.gaps.length}.** ${counts.gaps.join(", ") || "None."}`);
push();
push(`**Hold it back: ${counts.hold.length}.** ${counts.hold.join(", ") || "None."}`);
push();
push("Nothing reaches the first verdict, and that is the finding. Not one product");
push("has a confirmed price, a complete set of specifications and a recorded source");
push("for each of them at the same time.");
push();
push("## The shortest path to something worth showing");
push();
push("In order, and smaller is better: a partner shown six products whose every");
push("figure survives a question will believe the seventh. A partner shown twenty,");
push("eight of which cannot quote a price, will check all twenty.");
push();
push("1. **Confirm the eight prices, or drop those products from the showcase.**");
push("   Six of the eight red-light panels have no confirmed price, which is the");
push("   category a red-light brand would look at first. Cold plunges are the one");
push("   category where every price is real; that is the category to lead with.");
push("2. **Replace or remove the 24 prototype specification values.** Each one is");
push("   marked on the page, which is honest and still reads as unfinished. A");
push("   removed value costs a completeness point; an invented one costs the site.");
push("3. **Read the pages already recorded.** 124 of 196 attributes and 13 of 26");
push("   offer prices were relayed from search summaries rather than read from the");
push("   maker's page. The URLs are on file. This is ordinary work, needs no");
push("   agreement with anybody, and moves the largest number in this document.");
push("4. **Get images, or design around not having them.** 24 of 24 are");
push("   procedural. No partner conversation survives a catalogue with no product");
push("   photography, and a photograph found on a public page is not a licence.");
push("5. **Set `NEXT_PUBLIC_SITE_URL`, add robots and a sitemap** before anyone is");
push("   sent a link, or the canonical URLs point at localhost.");
push();
push("What is already true, and worth saying to a partner: the ranking is");
push("deterministic, weighted per category and explained on `/how-we-choose`; it");
push("cannot read affiliate status because that data is never passed to it; every");
push("figure on a product page names who reported it; a value nobody stated is");
push("shown as not stated rather than guessed; a bound is shown as a bound; and a");
push("price nobody confirmed is not shown as a price.");
push();

return lines.join("\n") + "\n";
}

// Written by `npm run partner:checklist`. A test compares the committed file
// to this output, so the document cannot quietly go stale against the data.
if (process.argv[1]?.endsWith("partner-checklist.ts")) {
  writeFileSync(CHECKLIST_PATH, buildPartnerChecklist());
  console.log(`Wrote ${CHECKLIST_PATH}`);
}
